#:kivy 2.3.0
<GameWidget>:
    canvas.before:
        Color:
            rgba: 0.3, 0.6, 0.4, 1
        Rectangle:
            pos: self.pos
            size: self.size

<GameUI>:
    orientation: 'vertical'

    # Felső rész: INFO UI
    BoxLayout:
        size_hint_y: 0.1
        canvas.before:
            Color:
                rgb: 0.1, 0.1, 0.1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: "Money: " + str(root.money)
        Label:
            text: "Health: " + str(root.health)
        Label:
            text: "Wave: " + str(root.wave)
    
    # Game Area
    BoxLayout:
        orientation: "horizontal"

        GameWidget:
            id: game_area

        BoxLayout:
            orientation: "vertical"
            size_hint_x: 0.25
            canvas.before:
                Color:
                    rgb: 0.2, 0.2, 0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Towers"
                height: 30
                size_hint_y: None
            Button:
                text: "Basic tower\nCost: 150"
                on_release: root.building_basic_tower()
            Button:
                text: "Soldier\nCost: 50"
                on_release: root.ids.game_area.summon_soldier()

